apiVersion: v2
name: kubePrometheusApp
description: A Helm chart that deploys the kube-prometheus-stack application.
type: application
version: "0.1.0"
dependencies:
- name: kube-prometheus-stack
  version: "75.6.1"
  repository: https://prometheus-community.github.io/helm-charts